export const STRINGS = {
  ar: {
    nav: {
      home: 'الرئيسية',
      search: 'البحث',
      orders: 'الطلبات',
      chat: 'الرسائل',
      profile: 'حسابي',
    },
    auth: {
      login: 'تسجيل الدخول',
      register: 'حساب جديد',
      otp: 'رمز التحقق',
      loginTitle: 'مرحباً بك',
      registerTitle: 'إنشاء حساب جديد',
      otpTitle: 'أدخل رمز التحقق',
      phone: 'رقم الهاتف',
      password: 'كلمة المرور',
      confirmPassword: 'تأكيد كلمة المرور',
      fullName: 'الاسم الكامل',
      forgotPassword: 'نسيت كلمة المرور؟',
      createAccount: 'إنشاء حساب',
      verify: 'تحقق',
      next: 'التالي',
      skip: 'تخطي',
      startNow: 'ابدأ الآن',
      termsAgree: 'أوافق على الشروط والأحكام',
      resendCode: 'إعادة إرسال الرمز',
      wrongCode: 'رمز غير صحيح',
      phonePlaceholder: '+212 600 000 000',
      passwordPlaceholder: 'أدخل كلمة المرور',
    },
    home: {
      greeting: 'مرحباً بك',
      searchPlaceholder: 'ماذا تبحث عن...',
      newRequest: 'طلب جديد',
      recentOrders: 'آخر طلباتك',
      categories: 'الفئات',
      activeOrder: 'طلب نشط',
      track: 'تتبع',
      noOrders: 'لا توجد طلبات',
      locationLabel: 'سافي، المغرب',
    },
    orders: {
      all: 'الكل',
      active: 'نشط',
      completed: 'مكتمل',
      cancelled: 'ملغي',
      noOrders: 'لا توجد طلبات هنا',
      noActiveOrders: 'ليس لديك طلبات قيد التنفيذ',
      noCompletedOrders: 'ليس لديك طلبات سابقة',
    },
    request: {
      newRequest: 'طلب جديد',
      delivery: 'توصيل',
      errand: 'مهمة',
      whatDoYouNeed: 'ماذا تريد؟',
      description: 'الوصف (اختياري)',
      descriptionPlaceholder: 'اكتب تفاصيل إضافية عن طلبك هنا',
      category: 'الفئة',
      pickupAddress: 'عنوان الاستلام',
      dropoffAddress: 'عنوان التسليم',
      estimatedPrice: 'السعر التقديري (بالدرهم)',
      submit: 'إرسال الطلب',
      analyzing: 'جاري التحقق من طلبك...',
      underReview: 'طلبك قيد المراجعة',
      rejected: 'تم رفض الطلب',
      rejectedExplanation: 'تم رفض الطلب لمخالفته شروط الاستخدام',
    },
    tracking: {
      tracking: 'تتبع طلبك',
      pending: 'قيد الانتظار',
      searchingDriver: 'نبحث عن سائق...',
      driverAssigned: 'تم تعيين سائق',
      inProgress: 'السائق في الطريق',
      pickedUp: 'تم استلام طلبك',
      delivered: 'تم توصيل الطلب بنجاح',
      confirmDelivery: 'نعم، استلمته',
      didNotArrive: 'لم يصل',
      cancel: 'إلغاء الطلب',
      cancelReason: 'سبب الإلغاء',
      eta: 'الوقت المتبقي',
      minutes: 'دقيقة',
    },
    chat: {
      typeMessage: 'اكتب رسالتك...',
      chatClosed: 'تم إغلاق هذه المحادثة',
      sendImage: 'إرسال صورة',
      noMessages: 'لا توجد رسائل',
    },
    profile: {
      profile: 'الملف الشخصي',
      addresses: 'العناوين المحفوظة',
      notifications: 'الإشعارات',
      helpCenter: 'مركز المساعدة',
      language: 'تغيير اللغة',
      version: 'الإصدار',
      logout: 'تسجيل الخروج',
      logoutConfirm: 'هل أنت متأكد من تسجيل الخروج؟',
      trustScore: 'مستوى الثقة',
    },
    common: {
      loading: 'جاري التحميل...',
      error: 'حدث خطأ، يرجى المحاولة لاحقاً',
      retry: 'إعادة المحاولة',
      confirm: 'تأكيد',
      cancel: 'إلغاء',
      save: 'حفظ',
      delete: 'حذف',
      yes: 'نعم',
      no: 'لا',
      ok: 'حسناً',
      back: 'رجوع',
      close: 'إغلاق',
      empty: 'فارغ',
    },
    moderation: {
      safe: 'آمن',
      review: 'مراجعة',
      rejected: 'مرفوض',
      pendingReview: 'في انتظار المراجعة',
    },
  },
  fr: {
    nav: {
      home: 'Accueil',
      search: 'Recherche',
      orders: 'Commandes',
      chat: 'Messages',
      profile: 'Profil',
    },
    auth: {
      login: 'Connexion',
      register: 'S\'inscrire',
      otp: 'Code de vérification',
      loginTitle: 'Bienvenue',
      registerTitle: 'Créer un compte',
      otpTitle: 'Entrez le code',
      phone: 'Numéro de téléphone',
      password: 'Mot de passe',
      confirmPassword: 'Confirmer le mot de passe',
      fullName: 'Nom complet',
      forgotPassword: 'Mot de passe oublié ?',
      createAccount: 'Créer mon compte',
      verify: 'Vérifier',
      next: 'Suivant',
      skip: 'Passer',
      startNow: 'Commencer',
      termsAgree: 'J\'accepte les conditions d\'utilisation',
      resendCode: 'Renvoyer le code',
      wrongCode: 'Code incorrect',
      phonePlaceholder: '+212 600 000 000',
      passwordPlaceholder: 'Entrez votre mot de passe',
    },
    home: {
      greeting: 'Bonjour',
      searchPlaceholder: 'Que cherchez-vous ?',
      newRequest: 'Nouvelle demande',
      recentOrders: 'Vos commandes récentes',
      categories: 'Catégories',
      activeOrder: 'Commande en cours',
      track: 'Suivre',
      noOrders: 'Aucune commande',
      locationLabel: 'Safi, Maroc',
    },
    orders: {
      all: 'Tout',
      active: 'En cours',
      completed: 'Terminées',
      cancelled: 'Annulées',
      noOrders: 'Aucune commande trouvée',
      noActiveOrders: 'Vous n\'avez aucune commande en cours',
      noCompletedOrders: 'Vous n\'avez aucune commande précédente',
    },
    request: {
      newRequest: 'Nouvelle demande',
      delivery: 'Livraison',
      errand: 'Commission',
      whatDoYouNeed: 'De quoi avez-vous besoin ?',
      description: 'Description (facultatif)',
      descriptionPlaceholder: 'Ajoutez plus de détails ici',
      category: 'Catégorie',
      pickupAddress: 'Adresse de récupération',
      dropoffAddress: 'Adresse de livraison',
      estimatedPrice: 'Prix estimé (DH)',
      submit: 'Envoyer la demande',
      analyzing: 'Vérification en cours...',
      underReview: 'Votre demande est en cours d\'examen',
      rejected: 'Demande refusée',
      rejectedExplanation: 'La demande a été refusée pour non-respect des règles',
    },
    tracking: {
      tracking: 'Suivi de commande',
      pending: 'En attente',
      searchingDriver: 'Recherche d\'un chauffeur...',
      driverAssigned: 'Chauffeur assigné',
      inProgress: 'Le chauffeur est en route',
      pickedUp: 'Commande récupérée',
      delivered: 'Commande livrée avec succès',
      confirmDelivery: 'Oui, j\'ai reçu la commande',
      didNotArrive: 'Non reçue',
      cancel: 'Annuler la commande',
      cancelReason: 'Raison de l\'annulation',
      eta: 'Temps d\'arrivée estimé',
      minutes: 'minutes',
    },
    chat: {
      typeMessage: 'Écrivez un message...',
      chatClosed: 'Cette conversation est fermée',
      sendImage: 'Envoyer une image',
      noMessages: 'Aucun message',
    },
    profile: {
      profile: 'Profil',
      addresses: 'Adresses sauvegardées',
      notifications: 'Notifications',
      helpCenter: 'Centre d\'aide',
      language: 'Changer la langue',
      version: 'Version',
      logout: 'Se déconnecter',
      logoutConfirm: 'Êtes-vous sûr de vouloir vous déconnecter ?',
      trustScore: 'Niveau de confiance',
    },
    common: {
      loading: 'Chargement en cours...',
      error: 'Une erreur s\'est produite',
      retry: 'Réessayer',
      confirm: 'Confirmer',
      cancel: 'Annuler',
      save: 'Enregistrer',
      delete: 'Supprimer',
      yes: 'Oui',
      no: 'Non',
      ok: 'D\'accord',
      back: 'Retour',
      close: 'Fermer',
      empty: 'Vide',
    },
    moderation: {
      safe: 'Sûr',
      review: 'À réviser',
      rejected: 'Rejeté',
      pendingReview: 'En attente',
    },
  },
} as const;
