import { useState } from 'react';
import { ActivityIndicator,Alert,Pressable,StyleSheet,Text,TextInput,View } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppIcon } from '@/components/ui/AppIcon';
import { BRAND,FONTS } from '@/constants/brand';
import { useAuthStore } from '@/store/authStore';
import { useUpdateProfile } from '@/hooks/mutations/useAuth';
import type { CustomerProfile } from '@/features/auth/services/authApi';

export default function ProfileEdit(){
  const router=useRouter(),user=useAuthStore(s=>s.user) as CustomerProfile|null,update=useUpdateProfile();
  const [name,setName]=useState(user?.full_name||''),[city,setCity]=useState(user?.city||''),[language,setLanguage]=useState<'ar'|'fr'|'en'>((user?.language as any)||'fr');
  async function save(){if(name.trim().length<2||!city.trim())return Alert.alert('Informations requises','Ajoutez votre nom et votre ville.');try{await update.mutateAsync({full_name:name.trim(),city:city.trim(),language});Alert.alert('Profil enregistre');router.back()}catch(e:any){Alert.alert('Erreur',e.message)}}
  return <SafeAreaView style={s.root}><View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><AppIcon name="chevron-back" size={22} color={BRAND.TEXT}/></Pressable><Text style={s.title}>Modifier le profil</Text></View><Text style={s.label}>Nom complet</Text><TextInput value={name} onChangeText={setName} style={s.input}/><Text style={s.label}>Ville</Text><TextInput value={city} onChangeText={setCity} style={s.input}/><Text style={s.label}>Langue</Text><View style={s.segment}>{(['ar','fr','en'] as const).map(value=><Pressable key={value} style={[s.choice,language===value&&s.active]} onPress={()=>setLanguage(value)}><Text style={s.choiceText}>{value.toUpperCase()}</Text></Pressable>)}</View><View style={s.phone}><View><Text style={s.phoneLabel}>WhatsApp verifie</Text><Text style={s.phoneValue}>{user?.phone_e164||user?.phone||'Non verifie'}</Text></View><AppIcon name="shield-checkmark" size={22} color="#128C7E"/></View><Pressable style={s.change} onPress={()=>router.push({pathname:'/(auth)/whatsapp',params:{mode:'attach',next:'/(tabs)/profile'}})}><AppIcon name="logo-whatsapp" size={19} color="#128C7E"/><Text style={s.changeText}>Changer le numero WhatsApp</Text></Pressable><Pressable style={[s.save,update.isPending&&{opacity:.6}]} onPress={save} disabled={update.isPending}>{update.isPending?<ActivityIndicator color="#fff"/>:<Text style={s.saveText}>Enregistrer</Text>}</Pressable></SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:BRAND.BG,paddingHorizontal:20},header:{height:70,flexDirection:'row',alignItems:'center',gap:14},back:{width:40,height:40,borderRadius:10,borderWidth:1,borderColor:BRAND.BORDER,alignItems:'center',justifyContent:'center'},title:{fontFamily:FONTS.DISPLAY,fontSize:21,color:BRAND.TEXT},label:{fontFamily:FONTS.SEMIBOLD,fontSize:13,color:BRAND.TEXT2,marginTop:18,marginBottom:8},input:{height:52,borderRadius:12,borderWidth:1,borderColor:BRAND.BORDER,backgroundColor:BRAND.SURFACE,paddingHorizontal:15,fontFamily:FONTS.BODY,fontSize:16,color:BRAND.TEXT},segment:{height:48,backgroundColor:'#EEECE5',borderRadius:12,padding:4,flexDirection:'row'},choice:{flex:1,borderRadius:9,alignItems:'center',justifyContent:'center'},active:{backgroundColor:BRAND.SURFACE},choiceText:{fontFamily:FONTS.SEMIBOLD,fontSize:13,color:BRAND.TEXT},phone:{marginTop:24,borderWidth:1,borderColor:BRAND.BORDER,borderRadius:12,padding:14,backgroundColor:BRAND.SURFACE,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},phoneLabel:{fontFamily:FONTS.BODY,fontSize:12,color:BRAND.TEXT3},phoneValue:{fontFamily:FONTS.SEMIBOLD,fontSize:14,color:BRAND.TEXT,marginTop:3},change:{height:50,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},changeText:{fontFamily:FONTS.SEMIBOLD,fontSize:13,color:'#128C7E'},save:{height:56,borderRadius:12,backgroundColor:BRAND.RED,alignItems:'center',justifyContent:'center',marginTop:20},saveText:{fontFamily:FONTS.DISPLAY,fontSize:16,color:'#fff'}});
