import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ActivityIndicator,BackHandler,KeyboardAvoidingView,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View,type TextInputProps } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { usePathname,useRouter } from 'expo-router';
import { Ionicons } from '@/components/ui/Ionicons';
import { BRAND,FONTS } from '@/constants/brand';
import { useLangStore } from '@/store/languageStore';

export function AuthScreenShell({title,subtitle,children,action,actionLabel,loading=false,disabled=false,onBack,showBack=true,backFallback='/(auth)/login',progress}: {title:string;subtitle?:string;children:ReactNode;action?:ReactNode;actionLabel?:string;loading?:boolean;disabled?:boolean;onBack?:()=>void;showBack?:boolean;backFallback?:string;progress?:number}){
  const router=useRouter();
  const pathname=usePathname();
  const rtl=useLangStore(s=>s.isRTL);
  const goBack=()=>{if(onBack)return onBack();if(router.canGoBack())return router.back();router.replace((pathname.endsWith('/login')?'/(auth)/welcome':backFallback) as any)};
  useEffect(()=>{if(Platform.OS!=='android'||!showBack)return;const subscription=BackHandler.addEventListener('hardwareBackPress',()=>{goBack();return true});return()=>subscription.remove()},[pathname,showBack,onBack]);
  return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined}>
    <View style={[s.top,rtl&&s.rtl]}>{showBack&&<Pressable style={s.back} onPress={goBack} accessibilityRole="button" accessibilityLabel="Retour" hitSlop={8}><Ionicons name={rtl?'chevron-forward':'chevron-back'} size={24} color={BRAND.TEXT}/></Pressable>}{progress!=null&&<View style={s.progress}><View style={[s.progressFill,{width:`${Math.max(8,progress*100)}%`}]} /></View>}</View>
    <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={[s.title,rtl&&s.right]}>{title}</Text>{subtitle&&<Text style={[s.subtitle,rtl&&s.right]}>{subtitle}</Text>}<View style={s.body}>{children}</View></ScrollView>
    {(action||actionLabel)&&<View style={s.footer}>{action||<PrimaryButton label={actionLabel!} loading={loading} disabled={disabled}/>}</View>}
  </KeyboardAvoidingView></SafeAreaView>
}
export function PrimaryButton({label,onPress,loading=false,disabled=false,color=BRAND.RED,icon}: {label:string;onPress?:()=>void;loading?:boolean;disabled?:boolean;color?:string;icon?:string}){const rtl=useLangStore(s=>s.isRTL);return <Pressable onPress={onPress} disabled={disabled||loading} style={({pressed})=>[s.primary,rtl&&directionStyles.rowReverse,{backgroundColor:color},(disabled||loading)&&s.disabled,pressed&&s.pressed]}>{loading?<ActivityIndicator color="#fff"/>:<>{icon&&<Ionicons name={icon as any} size={21} color="#fff"/>}<Text style={[s.primaryText,rtl&&directionStyles.right]}>{label}</Text></>}</Pressable>}
export function SecondaryButton({label,onPress,icon}: {label:string;onPress:()=>void;icon?:string}){const rtl=useLangStore(s=>s.isRTL);return <Pressable onPress={onPress} style={({pressed})=>[s.secondary,rtl&&directionStyles.rowReverse,pressed&&s.pressed]}>{icon&&<Ionicons name={icon as any} size={21} color={BRAND.TEXT}/>}<Text style={[s.secondaryText,rtl&&directionStyles.right]}>{label}</Text></Pressable>}
export function AuthTextField(props:TextInputProps&{label:string;error?:string;forceLTR?:boolean}){const rtl=useLangStore(s=>s.isRTL),[focused,setFocused]=useState(false),[revealed,setRevealed]=useState(false),isPassword=Boolean(props.secureTextEntry),forceLTR=Boolean(props.forceLTR||isPassword||props.keyboardType==='email-address'||props.keyboardType==='phone-pad');return <View style={s.field}><Text style={[s.label,rtl&&directionStyles.right]}>{props.label}</Text><View style={[fieldStyles.frame,rtl&&!forceLTR&&directionStyles.rowReverse,focused&&fieldStyles.focus,props.error&&fieldStyles.error]}><TextInput {...props} secureTextEntry={isPassword&&!revealed} onFocus={e=>{setFocused(true);props.onFocus?.(e)}} onBlur={e=>{setFocused(false);props.onBlur?.(e)}} placeholderTextColor={BRAND.TEXT3} style={[s.input,fieldStyles.textInput,rtl&&!forceLTR?directionStyles.rtlInput:directionStyles.ltrInput,props.style]}/>{isPassword&&<Pressable style={fieldStyles.reveal} onPress={()=>setRevealed(v=>!v)} accessibilityRole="button" accessibilityLabel={revealed?'Masquer le mot de passe':'Afficher le mot de passe'}><Ionicons name={revealed?'eye-off-outline':'eye-outline'} size={21} color={BRAND.TEXT2}/></Pressable>}</View>{props.error&&<Text style={[s.error,rtl&&directionStyles.right]}>{props.error}</Text>}</View>}
export function InlineNotice({text,tone='neutral'}:{text:string;tone?:'neutral'|'error'|'success'}){const rtl=useLangStore(s=>s.isRTL);return <View style={[s.notice,rtl&&directionStyles.rowReverse,tone==='error'&&s.noticeError,tone==='success'&&s.noticeSuccess]}><Ionicons name={tone==='error'?'alert-circle-outline':tone==='success'?'checkmark-circle-outline':'information-circle-outline'} size={19} color={tone==='error'?BRAND.ERROR:tone==='success'?BRAND.GREEN:BRAND.TEXT2}/><Text style={[s.noticeText,rtl&&directionStyles.right]}>{text}</Text></View>}
export function VerifiedContactRow({phone}:{phone:string}){const rtl=useLangStore(s=>s.isRTL);return <View style={[s.verified,rtl&&directionStyles.rowReverse]}><Ionicons name="logo-whatsapp" size={20} color="#128C7E"/><View style={s.flex}><Text style={[s.verifiedLabel,rtl&&directionStyles.right]}>WhatsApp</Text><Text style={[s.verifiedPhone,directionStyles.ltrInput]}>{phone}</Text></View><Ionicons name="checkmark-circle" size={21} color={BRAND.GREEN}/></View>}

const fieldStyles=StyleSheet.create({frame:{minHeight:56,borderWidth:1,borderColor:BRAND.INPUT_BORDER,borderRadius:16,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',overflow:'hidden'},focus:{borderColor:BRAND.RED,borderWidth:1.5},error:{borderColor:BRAND.ERROR},textInput:{flex:1,borderWidth:0,backgroundColor:'transparent'},reveal:{width:52,height:54,alignItems:'center',justifyContent:'center'}});
const directionStyles=StyleSheet.create({rowReverse:{flexDirection:'row-reverse'},right:{textAlign:'right',writingDirection:'rtl'},rtlInput:{textAlign:'right',writingDirection:'rtl'},ltrInput:{textAlign:'left',writingDirection:'ltr'}});

export function OtpCodeInput({value,onChange,onComplete,disabled=false,error=false}:{value:string;onChange:(value:string)=>void;onComplete?:(value:string)=>void;disabled?:boolean;error?:boolean}){
  const input=useRef<TextInput>(null),completed=useRef('');
  const clean=value.replace(/\D/g,'').slice(0,6);
  useEffect(()=>{if(clean.length===6&&clean!==completed.current){completed.current=clean;onComplete?.(clean)}if(clean.length<6)completed.current=''},[clean,onComplete]);
  return <Pressable accessibilityRole="button" accessibilityLabel="Six digit verification code" onPress={()=>input.current?.focus()} style={s.otpWrap}>
    <TextInput ref={input} value={clean} onChangeText={v=>onChange(v.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad" textContentType="oneTimeCode" autoComplete="one-time-code" maxLength={6} editable={!disabled} autoFocus style={s.otpHidden}/>
    {Array.from({length:6},(_,i)=><View key={i} style={[s.otpCell,clean[i]&&s.otpFilled,error&&s.otpError]}><Text style={s.otpText}>{clean[i]||''}</Text></View>)}
  </Pressable>
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#FFFEFA'},flex:{flex:1},top:{height:56,paddingHorizontal:20,flexDirection:'row',alignItems:'center',gap:14},rtl:{flexDirection:'row-reverse'},back:{width:44,height:44,alignItems:'center',justifyContent:'center'},progress:{height:4,backgroundColor:BRAND.LIGHT,borderRadius:2,flex:1,overflow:'hidden'},progressFill:{height:4,backgroundColor:BRAND.RED,borderRadius:2},content:{paddingHorizontal:24,paddingTop:18,paddingBottom:28},title:{fontFamily:FONTS.DISPLAY,fontSize:30,lineHeight:38,color:BRAND.TEXT},subtitle:{fontFamily:FONTS.BODY,fontSize:15,lineHeight:23,color:BRAND.TEXT2,marginTop:8},right:{textAlign:'right'},body:{marginTop:30},footer:{paddingHorizontal:24,paddingTop:12,paddingBottom:16,borderTopWidth:1,borderTopColor:'rgba(15,23,42,.06)',backgroundColor:'#FFFEFA'},primary:{height:56,borderRadius:16,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:10},primaryText:{fontFamily:FONTS.SEMIBOLD,fontSize:16,color:'#fff'},secondary:{height:56,borderRadius:16,borderWidth:1,borderColor:BRAND.BORDER,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:10},secondaryText:{fontFamily:FONTS.SEMIBOLD,fontSize:16,color:BRAND.TEXT},disabled:{opacity:.5},pressed:{opacity:.82},field:{marginBottom:18},label:{fontFamily:FONTS.SEMIBOLD,fontSize:13,color:BRAND.TEXT2,marginBottom:8},input:{minHeight:56,borderWidth:1,borderColor:BRAND.INPUT_BORDER,borderRadius:16,backgroundColor:'#fff',paddingHorizontal:16,fontFamily:FONTS.BODY,fontSize:16,color:BRAND.TEXT},inputFocus:{borderColor:BRAND.RED,borderWidth:1.5},inputError:{borderColor:BRAND.ERROR},error:{fontFamily:FONTS.BODY,fontSize:12,color:BRAND.ERROR,marginTop:6},notice:{minHeight:48,borderRadius:12,backgroundColor:BRAND.LIGHT,padding:12,flexDirection:'row',alignItems:'center',gap:9},noticeError:{backgroundColor:'#FEF2F2'},noticeSuccess:{backgroundColor:'#ECFDF5'},noticeText:{fontFamily:FONTS.BODY,fontSize:13,lineHeight:19,color:BRAND.TEXT2,flex:1},verified:{height:64,borderRadius:14,backgroundColor:'#ECFDF5',paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:11},verifiedLabel:{fontFamily:FONTS.SEMIBOLD,fontSize:12,color:'#126B60'},verifiedPhone:{fontFamily:FONTS.BODY,fontSize:13,color:BRAND.TEXT2,marginTop:2},otpWrap:{height:64,flexDirection:'row',gap:8,position:'relative'},otpHidden:{position:'absolute',width:1,height:1,opacity:0},otpCell:{flex:1,maxWidth:52,height:60,borderRadius:14,borderWidth:1.5,borderColor:BRAND.INPUT_BORDER,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},otpFilled:{borderColor:'#128C7E',backgroundColor:'#F0FDF9'},otpError:{borderColor:BRAND.ERROR},otpText:{fontFamily:FONTS.DISPLAY,fontSize:23,color:BRAND.TEXT}});
