import type { Lang } from '@/store/languageStore';

const COPY = {
  ar: {
    title: 'تأكيد الطلب',
    subtitle: 'راجع العنوان والطلب قبل التأكيد',
    back: 'رجوع',
    address: 'عنوان التوصيل',
    change: 'تغيير',
    addressMissing: 'أضف عنوان توصيل للمتابعة',
    addressIncomplete: 'يحتاج هذا العنوان إلى موقع دقيق قبل الطلب.',
    completeAddress: 'إكمال عنوان التوصيل',
    addressLoadError: 'تعذر تحميل عنوانك.',
    order: 'طلبك',
    editCart: 'تعديل السلة',
    quantity: 'الكمية',
    payment: 'طريقة الدفع',
    cash: 'الدفع نقداً عند الاستلام',
    note: 'ملاحظة للتوصيل',
    notePlaceholder: 'مثال: الطابق الثاني، اتصل عند الوصول',
    summary: 'ملخص السعر',
    subtotal: 'المنتجات',
    delivery: 'التوصيل',
    serviceFee: 'رسوم الخدمة',
    discount: 'الخصم',
    total: 'المجموع',
    placeOrder: 'تأكيد الطلب',
    emptyCart: 'سلتك فارغة.',
    quoteUnavailable: 'تعذر تأكيد الأسعار الحالية.',
    storeUnavailable: 'المتجر لا يستقبل الطلبات حالياً.',
    retry: 'إعادة المحاولة',
    signInRequired: 'سجّل الدخول لإتمام الطلب.',
    maintenance: 'الخدمة غير متاحة مؤقتاً. حاول لاحقاً.',
    orderFailed: 'تعذر إنشاء الطلب. حاول مرة أخرى.',
    loading: 'جارٍ تحميل تفاصيل الطلب...',
  },
  fr: {
    title: 'Confirmer la commande',
    subtitle: 'Vérifiez votre adresse et votre commande',
    back: 'Retour',
    address: 'Adresse de livraison',
    change: 'Modifier',
    addressMissing: 'Ajoutez une adresse de livraison pour continuer',
    addressIncomplete: 'Cette adresse nécessite une position précise avant de commander.',
    completeAddress: "Compléter l'adresse",
    addressLoadError: 'Impossible de charger votre adresse.',
    order: 'Votre commande',
    editCart: 'Modifier le panier',
    quantity: 'Quantité',
    payment: 'Mode de paiement',
    cash: 'Paiement en espèces à la livraison',
    note: 'Note de livraison',
    notePlaceholder: "Exemple : 2e étage, appelez à l'arrivée",
    summary: 'Récapitulatif',
    subtotal: 'Produits',
    delivery: 'Livraison',
    serviceFee: 'Frais de service',
    discount: 'Réduction',
    total: 'Total',
    placeOrder: 'Confirmer la commande',
    emptyCart: 'Votre panier est vide.',
    quoteUnavailable: 'Impossible de confirmer les prix actuels.',
    storeUnavailable: "Le magasin n'accepte pas de commandes actuellement.",
    retry: 'Réessayer',
    signInRequired: 'Connectez-vous pour finaliser la commande.',
    maintenance: 'Le service est temporairement indisponible. Réessayez plus tard.',
    orderFailed: 'Impossible de créer la commande. Réessayez.',
    loading: 'Chargement de la commande...',
  },
  en: {
    title: 'Confirm order',
    subtitle: 'Review your address and order',
    back: 'Back',
    address: 'Delivery address',
    change: 'Change',
    addressMissing: 'Add a delivery address to continue',
    addressIncomplete: 'This address needs a precise location before ordering.',
    completeAddress: 'Complete delivery address',
    addressLoadError: 'Could not load your address.',
    order: 'Your order',
    editCart: 'Edit cart',
    quantity: 'Quantity',
    payment: 'Payment method',
    cash: 'Cash on delivery',
    note: 'Delivery note',
    notePlaceholder: 'Example: second floor, call on arrival',
    summary: 'Price summary',
    subtotal: 'Items',
    delivery: 'Delivery',
    serviceFee: 'Service fee',
    discount: 'Discount',
    total: 'Total',
    placeOrder: 'Place order',
    emptyCart: 'Your cart is empty.',
    quoteUnavailable: 'Current prices could not be confirmed.',
    storeUnavailable: 'The store is not accepting orders right now.',
    retry: 'Try again',
    signInRequired: 'Sign in to complete your order.',
    maintenance: 'The service is temporarily unavailable. Try again later.',
    orderFailed: 'The order could not be created. Try again.',
    loading: 'Loading your order...',
  },
} as const;

export function checkoutCopy(lang: Lang) {
  return COPY[lang] ?? COPY.fr;
}
