// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/search-futuristic/CyberGradient.tsx": () => import("../components/mockups/search-futuristic/CyberGradient.tsx"),
  "./components/mockups/search-futuristic/Hologram.tsx": () => import("../components/mockups/search-futuristic/Hologram.tsx"),
  "./components/mockups/search-futuristic/NeonGlass.tsx": () => import("../components/mockups/search-futuristic/NeonGlass.tsx")
};
