import { useState } from 'react';
import { useLocalSearchParams,useRouter } from 'expo-router';
import { AuthScreenShell,AuthTextField,InlineNotice,PrimaryButton } from '@/features/auth/components/AuthPrimitives';
import { routeForCustomer,saveOnboardingAddress } from '@/features/auth/services/authApi';
import { useAuthStore } from '@/store/authStore';
import { useLangStore } from '@/store/languageStore';

export default function ConfirmAddressScreen(){
  const router=useRouter(),params=useLocalSearchParams<{lat:string;lng:string;city?:string;address?:string;source?:string}>(),setUser=useAuthStore(s=>s.setUser),{lang}=useLangStore();
  const[city,setCity]=useState(params.city||''),[address,setAddress]=useState(params.address||''),[building,setBuilding]=useState(''),[landmark,setLandmark]=useState(''),[instructions,setInstructions]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const ar=lang==='ar',en=lang==='en';
  async function save(){const lat=Number(params.lat),lng=Number(params.lng);if(!city.trim()||address.trim().length<2||!Number.isFinite(lat)||!Number.isFinite(lng))return setError(ar?'أكد المدينة والعنوان.':en?'Confirm the city and address.':'Confirmez la ville et l adresse.');setLoading(true);setError('');const result=await saveOnboardingAddress({city:city.trim(),address:address.trim(),lat,lng,building_info:building.trim()||undefined,nearby_landmark:landmark.trim()||undefined,delivery_instructions:instructions.trim()||undefined,location_source:params.source==='gps'?'gps':'manual_map_pin'});setLoading(false);if(result.error||!result.data)return setError(ar?'تعذر حفظ العنوان.':en?'Unable to save address.':'Impossible d enregistrer l adresse.');setUser(result.data);router.replace(routeForCustomer(result.data) as never)}
  return <AuthScreenShell title={ar?'تأكيد عنوان التوصيل':en?'Confirm delivery address':'Confirmer l adresse'} subtitle={ar?'أضف التفاصيل التي تساعد المندوب على الوصول إليك.':en?'Add details that help the courier find you.':'Ajoutez les details utiles au livreur.'} progress={.9} action={<PrimaryButton label={ar?'حفظ ومتابعة':en?'Save and continue':'Enregistrer et continuer'} loading={loading} disabled={!city||!address} onPress={save}/>}><AuthTextField label={ar?'المدينة':en?'City':'Ville'} value={city} onChangeText={setCity}/><AuthTextField label={ar?'العنوان بالتفصيل':en?'Detailed address':'Adresse detaillee'} value={address} onChangeText={setAddress} multiline/><AuthTextField label={ar?'المبنى / الطابق / الشقة':en?'Building / floor / apartment':'Immeuble / etage / appartement'} value={building} onChangeText={setBuilding}/><AuthTextField label={ar?'معلم قريب':en?'Nearby landmark':'Point de repere'} value={landmark} onChangeText={setLandmark}/><AuthTextField label={ar?'تعليمات التوصيل (اختياري)':en?'Delivery instructions (optional)':'Instructions de livraison (facultatif)'} value={instructions} onChangeText={setInstructions} multiline/>{error?<InlineNotice text={error} tone="error"/>:null}</AuthScreenShell>;
}
