import { useEffect,useRef,useState } from 'react';
import { ActivityIndicator,FlatList,Pressable,StyleSheet,Text,TextInput,View } from 'react-native';
import MapView,{Marker,Region} from 'react-native-maps';
import { useRouter } from 'expo-router';
import { Ionicons } from '@/components/ui/Ionicons';
import { BRAND,FONTS } from '@/constants/brand';
import { getLocationConfig,reverseLocation,searchLocations,type LocationResult } from '@/lib/locationApi';
import { useLangStore } from '@/store/languageStore';

export default function MapPinScreen(){
  const router=useRouter(),map=useRef<MapView>(null),{lang,isRTL}=useLangStore();const[region,setRegion]=useState<Region|null>(null),[query,setQuery]=useState(''),[results,setResults]=useState<LocationResult[]>([]),[loading,setLoading]=useState(true),[searching,setSearching]=useState(false),[error,setError]=useState('');
  useEffect(()=>{getLocationConfig().then(r=>setRegion({latitude:r.initial_region.latitude,longitude:r.initial_region.longitude,latitudeDelta:r.initial_region.latitude_delta,longitudeDelta:r.initial_region.longitude_delta})).catch(()=>setError(lang==='ar'?'تعذر تحميل الخريطة.':'Map unavailable.')).finally(()=>setLoading(false))},[]);
  async function search(){if(query.trim().length<3)return;setSearching(true);setError('');try{setResults(await searchLocations(query.trim()))}catch{setError(lang==='ar'?'تعذر البحث حاليا.':'Search is temporarily unavailable.')}finally{setSearching(false)}}
  function choose(item:LocationResult){const next={latitude:item.latitude,longitude:item.longitude,latitudeDelta:0.012,longitudeDelta:0.012};setRegion(next);setResults([]);map.current?.animateToRegion(next,300)}
  async function confirm(){if(!region)return;setLoading(true);try{const found=await reverseLocation(region.latitude,region.longitude);router.push({pathname:'/(auth)/confirm-address',params:{lat:String(region.latitude),lng:String(region.longitude),city:found?.city||'',address:found?.address||'',source:'manual_map_pin'}})}catch{setError(lang==='ar'?'تعذر تأكيد الموقع.':'Unable to confirm location.')}finally{setLoading(false)}}
  if(loading&&!region)return <View style={s.center}><ActivityIndicator color={BRAND.RED}/></View>;
  return <View style={s.root}>{region?<MapView ref={map} style={StyleSheet.absoluteFill} initialRegion={region} onRegionChangeComplete={setRegion}><Marker coordinate={region} draggable onDragEnd={e=>setRegion({...region,...e.nativeEvent.coordinate})}/></MapView>:null}<View style={[s.top,isRTL&&s.rowReverse]}><Pressable style={s.icon} onPress={()=>router.back()}><Ionicons name={isRTL?'chevron-forward':'chevron-back'} size={24} color={BRAND.TEXT}/></Pressable><TextInput value={query} onChangeText={setQuery} onSubmitEditing={search} placeholder={lang==='ar'?'ابحث عن شارع أو حي':lang==='en'?'Search street or area':'Rechercher une rue ou un quartier'} style={[s.search,isRTL&&s.right]}/><Pressable style={s.icon} onPress={search}>{searching?<ActivityIndicator size="small" color={BRAND.RED}/>:<Ionicons name="search" size={21} color={BRAND.RED}/>}</Pressable></View>{results.length?<FlatList data={results} keyExtractor={(x,i)=>x.place_id||String(i)} style={s.results} renderItem={({item})=><Pressable style={s.result} onPress={()=>choose(item)}><Text style={[s.resultText,isRTL&&s.right]}>{item.label}</Text></Pressable>}/>:null}<View style={s.bottom}>{error?<Text style={s.error}>{error}</Text>:null}<Pressable style={s.confirm} onPress={confirm} disabled={!region||loading}>{loading?<ActivityIndicator color="#fff"/>:<Text style={s.confirmText}>{lang==='ar'?'تأكيد هذا الموقع':lang==='en'?'Confirm this location':'Confirmer ce lieu'}</Text>}</Pressable></View></View>;
}
const s=StyleSheet.create({root:{flex:1},center:{flex:1,alignItems:'center',justifyContent:'center'},rowReverse:{flexDirection:'row-reverse'},right:{textAlign:'right'},top:{position:'absolute',top:54,left:16,right:16,height:56,flexDirection:'row',alignItems:'center',gap:8},icon:{width:48,height:48,borderRadius:14,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},search:{flex:1,height:52,borderRadius:14,backgroundColor:'#fff',paddingHorizontal:15,fontFamily:FONTS.BODY,color:BRAND.TEXT},results:{position:'absolute',top:116,left:72,right:72,maxHeight:220,backgroundColor:'#fff',borderRadius:14},result:{padding:14,borderBottomWidth:1,borderBottomColor:BRAND.BORDER},resultText:{fontFamily:FONTS.BODY,color:BRAND.TEXT},bottom:{position:'absolute',left:16,right:16,bottom:24,backgroundColor:'#fff',borderRadius:18,padding:14},confirm:{height:56,borderRadius:15,backgroundColor:BRAND.RED,alignItems:'center',justifyContent:'center'},confirmText:{fontFamily:FONTS.SEMIBOLD,color:'#fff',fontSize:16},error:{fontFamily:FONTS.BODY,color:BRAND.ERROR,textAlign:'center',marginBottom:10}});
